### ISSUE TITLE
 clippy::map_clone suggestion doesn't compile in 1.77.0

### ISSUE THREAD

**Issue by eric-seppanen** [rust-lang/rust-clippy#12359]
### Summary

The `map_clone` lint (in rust 1.77) suggests a fix that does not compile.

Seems closely related to #12357. This doesn't happen under 1.76.

### Lint Name

map_clone

### Reproducer

I tried this code:

```rust
use std::ops::Deref;
use std::sync::Arc;

pub struct Wrap<T> {
    inner: T,
}

impl<T> Deref for Wrap<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

pub struct Thing {
    current: Vec<Wrap<Arc<u32>>>,
}

impl Thing {
    pub fn first(&self) -> Option<Arc<u32>> {
        self.current.first().map(|p| Arc::clone(p))
    }
}
```

I saw this happen:

```plaintext
warning: you are explicitly cloning with `.map()`
  --> src/lib.rs:22:9
   |
22 |         self.current.first().map(|p| Arc::clone(p))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider calling the dedicated `cloned` method: `self.current.first().cloned()`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#map_clone
   = note: `#[warn(clippy::map_clone)]` on by default

```

If I apply the suggestion:
```plaintext
error[E0277]: the trait bound `Wrap<Arc<u32>>: Clone` is not satisfied
    --> src/lib.rs:22:30
     |
22   |         self.current.first().cloned()
     |                              ^^^^^^ the trait `Clone` is not implemented for `Wrap<Arc<u32>>`
     |
note: required by a bound in `Option::<&T>::cloned`
    --> .../library/core/src/option.rs:1884:12
     |
1882 |     pub fn cloned(self) -> Option<T>
     |            ------ required by a bound in this associated function
1883 |     where
1884 |         T: Clone,
     |            ^^^^^ required by this bound in `Option::<&T>::cloned`
help: consider annotating `Wrap<Arc<u32>>` with `#[derive(Clone)]`
     |
4    + #[derive(Clone)]
5    | pub struct Wrap<T> {
     |

```

I expected to see this happen:

Either no lint should fire, or the suggested fix should compile.

### Version

```text
rustc 1.77.0 (aedd173a2 2024-03-17)
binary: rustc
commit-hash: aedd173a2c086e558c2b66d3743b344f977621a7
commit-date: 2024-03-17
host: x86_64-unknown-linux-gnu
release: 1.77.0
LLVM version: 17.0.6
```

**Comment by eric-seppanen** [comment]
Retested on the 1.77.0 release; verified the problem is still present.

**Comment by eric-seppanen** [comment]
Seems to be gone on 1.79.0.
