### ISSUE TITLE
Primary span for `clippy::redundant-locals` points at the initial def, not the rebinding

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust-clippy#11625]
### Summary

The srcloc for the primary span is pointing at the original variable definition, rather than the redundant redefinition, which means that you can frequently end up at a wrong place to investigate the issue and flow gets interrupted.

### Reproducer

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e51df3b7d7a48e1b5f489203d0affd4c

I tried this code:

```rust
#![deny(clippy::redundant_locals)]

fn main() {
    let apple = 42;
    let apple = apple;
}
```

I expected to see this happen:

```
error: redundant redefinition of a binding
 --> src/main.rs:5:5
  |
4 |     let apple = 42;
  |         ^^^^^
5 |     let apple = apple;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = help: remove the redefinition of `apple`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
```

Instead, this happened (note the line `SrcLoc` for the primary span):

```
error: redundant redefinition of a binding
 --> src/main.rs:4:9
  |
4 |     let apple = 42;
  |         ^^^^^
5 |     let apple = apple;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = help: remove the redefinition of `apple`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_locals
```

### Version

```text
Build using the Nightly version: 1.75.0-nightly

(2023-10-05 cae0791da47bb01f1688)
```
