### PR TITLE
New Lint: Iter nth zero

### LINKED ISSUE #4957: New lint: iter_nth_zero
Suggest  replacing `iter.nth(0)` with `iter.next()`.

### PR DESCRIPTION
**Pull request by bradsherman**
Check for the use of `iter.nth(0)` and encourage `iter.next()` instead as it is more readable

changelog: add new lint when `iter.nth(0)` is used

Fixes #4957

### CODE REVIEW

File: clippy_lints/src/iter_nth_zero.rs [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+  style,
+  "replace `iter.nth(0)` with `iter.next()`"
+}
+
+declare_lint_pass!(IterNthZero => [ITER_NTH_ZERO]);
+
+impl EarlyLintPass for IterNthZero {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &Expr) {
+        if let ExprKind::MethodCall(PathSegment { ident, .. }, args) = &expr.kind {
+            if ident.name.as_str() == "nth" {
```
Comment (krishna-veerareddy) [inline clippy_lints/src/iter_nth_zero.rs]: This would lint on any method call called `nth` which isn't what we want so we should check the type of the receiver to make sure it implements the `std::iter::Iterator` trait.

File: clippy_lints/src/iter_nth_zero.rs [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+  pub ITER_NTH_ZERO,
+  style,
+  "replace `iter.nth(0)` with `iter.next()`"
+}
+
+declare_lint_pass!(IterNthZero => [ITER_NTH_ZERO]);
+
+impl EarlyLintPass for IterNthZero {
+    fn check_expr(&mut self, cx: &EarlyContext<'_>, expr: &Expr) {
+        if let ExprKind::MethodCall(PathSegment { ident, .. }, args) = &expr.kind {
```
Comment (krishna-veerareddy) [inline clippy_lints/src/iter_nth_zero.rs]: Consider using the `if_chain` macro to reduce the rightward drift of nested if's.

File: clippy_lints/src/iter_nth_zero.rs (hunk 1 above)
Comment (mikerite) [reply clippy_lints/src/iter_nth_zero.rs]: Use `match_trait_method` in the `utils` module for an easy way doing this.

File: clippy_lints/src/iter_nth_zero.rs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+            if ident.name.as_str() == "nth" {
+                if let ExprKind::Lit(literal) = &args[1].kind {
+                    if literal.token.symbol.as_str() == "0" {
```
Comment (mikerite) [inline clippy_lints/src/iter_nth_zero.rs]: Rather, use constant evaluation to check if the literal is `0`. Check out the `iterator_step_by_zero` lint does it if you want an example.

File: clippy_lints/src/iter_nth_zero.rs (hunk 1 above)
Comment (bradsherman) [reply clippy_lints/src/iter_nth_zero.rs]: good catch, thanks for pointing out that helper method

File: clippy_lints/src/iter_nth_zero.rs (hunk 3 above)
Comment (bradsherman) [reply clippy_lints/src/iter_nth_zero.rs]: thanks for pointing that out, I thought that comparison looked a little weird

File: clippy_lints/src/iter_nth_zero.rs (hunk 2 above)
Comment (bradsherman) [reply clippy_lints/src/iter_nth_zero.rs]: done, thanks for pointing that out I haven't seen it before

File: clippy_lints/src/methods/mod.rs [hunk 4]
```diff
@@ -756,6 +757,32 @@ declare_clippy_lint! {
...
+  ///  let x = s.iter().nth(0);
+  ///
+  /// // Good
+  ///  let mut s = HashSet::new();
+  ///  s.insert(1);
+  ///  let x = s.iter().next();
+  /// ```
+  pub ITER_NTH_ZERO,
+  style,
+  "replace `iter.nth(0)` with `iter.next()`"
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: Indentation

File: clippy_lints/src/methods/mod.rs [hunk 5]
```diff
@@ -2023,6 +2054,21 @@ fn lint_iter_nth<'a, 'tcx>(
...
+    if_chain! {
+        if match_trait_method(cx, expr, &paths::ITERATOR);
+        if let Some((Constant::Int(0), _)) = constant(cx, cx.tables, &nth_args[1]);
+        then {
+            span_lint(
+                cx,
+                ITER_NTH_ZERO,
+                expr.span,
+                "called `.nth(0)` on a `std::iter::Iterator`. Calling `.next()` is more readable",
+            );
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```rust
let mut applicability = Applicability::MachineApplicable;
span_lint_and_sugg(
    cx,
    ITER_NTH_ZERO,
    expr.span,
    "called `.nth(0)` on a `std::iter::Iterator`"
    "try calling",
    format!("{}.next()", snippet_with_applicability(nth_args[0].span, "..", &mut applicability),
    applicability,
);
```

File: tests/ui/iter_nth_zero.rs [hunk 6]
```diff
@@ -0,0 +1,24 @@
+#![warn(clippy::iter_nth_zero)]
```
Comment (flip1995) [inline tests/ui/iter_nth_zero.rs]:
```suggestion
// run-rustfix

#![warn(clippy::iter_nth_zero)]
```

File: tests/ui/iter_nth_zero.rs [hunk 7]
```diff
@@ -0,0 +1,24 @@
...
+    f.nth(0); // lint does not apply here
+
+    let mut s = HashSet::new();
+    s.insert(1);
+    let x = s.iter().nth(0);
+
+    let mut s2 = HashSet::new();
+    s2.insert(2);
+    let mut iter = s2.iter();
+    let y = iter.nth(0);
```
Comment (flip1995) [inline tests/ui/iter_nth_zero.rs]: can you add a test for `...nth(0).unwrap()`?

File: clippy_lints/src/methods/mod.rs (hunk 4 above)
Comment (bradsherman) [reply clippy_lints/src/methods/mod.rs]: good catch

File: clippy_lints/src/methods/mod.rs (hunk 5 above)
Comment (bradsherman) [reply clippy_lints/src/methods/mod.rs]: done

File: tests/ui/iter_nth_zero.rs (hunk 6 above)
Comment (bradsherman) [reply tests/ui/iter_nth_zero.rs]: done

**Comment by bradsherman** [comment]
I made the requested changes, however after rebasing on master sometime yesterday I could not compile `clippy_lints`: 

```
error[E0107]: wrong number of lifetime arguments: expected 0, found 1
  --> clippy_lints/src/zero_div_zero.rs:29:75
   |
29 |     fn check_expr(&mut self, cx: &LateContext<'a, 'tcx>, expr: &'tcx Expr<'_>) {
   |                                                                           ^^ unexpected lifetime argument
```

This happens in around ~900 other places as well.

File: tests/ui/iter_nth_zero.rs (hunk 7 above)
Comment (bradsherman) [reply tests/ui/iter_nth_zero.rs]: done

**Comment by bradsherman** [comment]
I have replicated the issue even when cloning a new repo from rust-lang:rust-clippy. Here's my rustc version:
```
rustc 1.42.0-nightly (0de96d37f 2019-12-19)
```
I'm only pointing this out because I can't build locally in order ensure all the tests pass

**Comment by JohnTitor** [comment]
@bradsherman It's because there is a difference between nightly and master rustc. Clippy is built for master, not nightly. You can use `rustup-toolchain-install-master`.

ref. https://github.com/rust-lang/rust-clippy/blob/master/CONTRIBUTING.md#fixing-build-failures-caused-by-rust

**Comment by bradsherman** [comment]
@JohnTitor thanks, that fixed it. Sorry I missed that in the docs.

File: clippy_lints/src/methods/mod.rs [hunk 8]
```diff
@@ -756,6 +757,32 @@ declare_clippy_lint! {
...
+    /// is more readable.
+    ///
+    /// **Known problems:** None.
+    ///
+    /// **Example:**
+    ///
+    /// ```rust,ignore
+    /// // Bad
+    ///  let mut s = HashSet::new();
+    ///  s.insert(1);
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: can you add a `#` in front of those two lines, so they won't be shown in the documentation (since there not relevant for the prupose of the lint).

Also I don't see, why this doc test should be `ignore`.

File: clippy_lints/src/methods/mod.rs [hunk 9]
```diff
@@ -756,6 +757,32 @@ declare_clippy_lint! {
...
+    ///  let x = s.iter().nth(0);
+    ///
+    /// // Good
+    ///  let mut s = HashSet::new();
+    ///  s.insert(1);
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]: same here

Comment (bradsherman) [reply clippy_lints/src/methods/mod.rs]: done

File: clippy_lints/src/methods/mod.rs (hunk 8 above)
Comment (bradsherman) [reply clippy_lints/src/methods/mod.rs]: done

File: src/lintlist/mod.rs [hunk 10]
```diff
@@ -875,6 +875,13 @@ pub const ALL_LINTS: [Lint; 343] = [
         deprecation: None,
         module: "methods",
     },
+    Lint {
```
Comment (krishna-veerareddy) [inline src/lintlist/mod.rs]: Hey you need to run `./util/dev update_lints` from the project root to update the lint count. Needs to be 344 now.

Comment (bradsherman) [reply src/lintlist/mod.rs]: yep, working on it now. I've been having trouble while working on this with certain tests failing because the stdout does not match. It is because there are a few extra lines like this:

```
-error[E0465]: multiple rlib candidates for `regex` found
-   |
-   = note: candidate #1: /c/Users/bsher/Documents/code/rust-projects/rust-clippy/target/debug/deps/libregex-4597a03e6ae80e63.rlib
-   = note: candidate #2: /c/Users/bsher/Documents/code/rust-projects/rust-clippy/target/debug/deps/libregex-4e8ce8deb48c4f7c.rlib
```

It usually resolves itself after a while or with a `cargo clean`, but I haven't been able to figure out exactly what the cause/fix is, any ideas?

Comment (krishna-veerareddy) [reply src/lintlist/mod.rs]: Yeah I have the same issue as well. Usually I just run `./test/ui/update-all-references.sh` and then ignore the modified regex test cases by not committing them but maybe there are other ways to deal with it that I am not aware of.

Comment (bradsherman) [reply src/lintlist/mod.rs]: okay cool, just wanted to make sure I wasn't doing something wrong. Thanks!

Comment (flip1995) [reply src/lintlist/mod.rs]: Running `cargo clean` and recompiling solves this issue. Or just running `rm target/debug/deps/libregex*` should also solve this.

Another thing to do here is to only update the test, that is touched by your PR. The command to do that is in the output of a failed test. I think it's right below the stderr diff. To find it, you can grep for `update-references` (without `all`).

File: clippy_lints/src/methods/mod.rs [hunk 11]
```diff
@@ -756,6 +757,32 @@ declare_clippy_lint! {
...
+    /// **What it does:** Checks for the use of `iter.nth(0)`.
+    ///
+    /// **Why is this bad?** `iter.nth(0)` is unnecessary, and `iter.next()`
+    /// is more readable.
+    ///
+    /// **Known problems:** None.
+    ///
+    /// **Example:**
+    ///
+    /// ```rust
```
Comment (flip1995) [inline clippy_lints/src/methods/mod.rs]:
```suggestion
    /// ```rust
    /// # use std::collections::HashSet;
```

Comment (bradsherman) [reply clippy_lints/src/methods/mod.rs]: yep just about to push it up, thanks for bearing with me!

**Comment by bradsherman** [comment]
thanks all for helping with my first open source contribution! 😃🎉
