### PR TITLE
Fix if_same_then_else false positive

### PR DESCRIPTION
**Pull request by jorpic**
This fixes false positive in #3559.
The problem was that `SpanlessEq` does not check patterns in declarations. So this two blocks considered equal.
```rust
if true {
    let (x, y) = foo();
} else {
   let (y, x) = foo();
}
```
Not sure if the proposed change is safe as `SpanlessEq` is used extensively in other lints, but I tried hard to come up with counterexample and failed.

### CODE REVIEW

**Comment by jorpic** [comment]
Don't understand how my change causes build failure.
Seems that `hir::ExprKind::Err` was introduced in https://github.com/rust-lang/rust/commit/a5c52c72ae3c1d8b3896756541b115a1d5ea94b7 11 days ago.

Should I address these errors in this PR?

```
error[E0004]: non-exhaustive patterns: `Err` not covered
   --> clippy_lints\src\utils\inspector.rs:172:11
    |
172 |     match expr.node {
    |           ^^^^^^^^^ pattern `Err` not covered
error[E0004]: non-exhaustive patterns: `Err` not covered
   --> clippy_lints\src\loops.rs:691:11
    |
691 |     match expr.node {
    |           ^^^^^^^^^ pattern `Err` not covered
error[E0004]: non-exhaustive patterns: `Err` not covered
   --> clippy_lints\src\utils\author.rs:205:15
    |
205 |         match expr.node {
    |               ^^^^^^^^^ pattern `Err` not covered
error[E0004]: non-exhaustive patterns: `Err` not covered
   --> clippy_lints\src\utils\hir_utils.rs:410:15
    |
410 |         match e.node {
    |               ^^^^^^ pattern `Err` not covered
error[E0004]: non-exhaustive patterns: `Err` not covered
  --> clippy_lints\src\utils\sugg.rs:58:19
   |
58 |             match expr.node {
   |                   ^^^^^^^^^ pattern `Err` not covered
error[E0004]: non-exhaustive patterns: `Err` not covered
   --> clippy_lints\src\utils\sugg.rs:128:15
    |
128 |         match expr.node {
    |               ^^^^^^^^^ pattern `Err` not covered
error: aborting due to 6 previous errors
```

**Comment by oli-obk** [comment]
You probably just have an outdated master branch. If you rebase over the master branch of this repository, everything should work again

**Comment by flip1995** [comment]
Fixed in #3591

File: tests/ui/copies.rs [hunk 1]
```diff
@@ -335,6 +335,17 @@ fn if_same_then_else() -> Result<&'static str, ()> {
         let foo = "";
         return Ok(&foo[0..]);
     }
+
+    // See #3559
```
Comment (matthiaskrgr) [inline tests/ui/copies.rs]: nit: I'd like this line to be slightly more descriptive, something like
````    // false positive if_same_then_else, let(x,y) vs let(y,x), see #3559````

Comment (jorpic) [reply tests/ui/copies.rs]: Fixed that. Thanks for feedback!
